import { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { ChevronDown, MoreVertical, Plus, Trash2, AlertTriangle, Copy, Check, Loader2, ToggleLeft, ToggleRight, Activity, Server, Zap, Shield, RefreshCw, Container, Globe, WifiOff, Terminal, HardDrive, MapPin, Cpu, MemoryStick, Eye } from 'lucide-react';
import StatusBadge from '../components/StatusBadge';
import OrangeLink from '../components/OrangeLink';

// Mock data for demonstration
const initialPods = [
  { id: 1, name: 'pod-web-frontend-7d8f9c', status: 'running', cpu: 45, memory: 1.2, nodeType: 'web', ip: '10.0.1.15', age: '12d', containers: '2/2', restarts: 0, ready: true },
  { id: 2, name: 'pod-api-backend-3a2b1c', status: 'running', cpu: 62, memory: 2.4, nodeType: 'api', ip: '10.0.1.22', age: '8d', containers: '3/3', restarts: 1, ready: true },
  { id: 3, name: 'pod-worker-queue-5e6f7g', status: 'pending', cpu: 12, memory: 0.5, nodeType: 'worker', ip: '10.0.1.31', age: '2d', containers: '1/2', restarts: 0, ready: false },
  { id: 4, name: 'pod-cache-redis-9h0i1j', status: 'running', cpu: 28, memory: 3.1, nodeType: 'cache', ip: '10.0.1.45', age: '15d', containers: '1/1', restarts: 0, ready: true },
];

const initialNodes = [
  { id: 1, name: 'node-prod-01', status: 'running', cpu: 71, memory: 14.2, internalIp: '10.0.0.1', externalIp: '192.168.1.10', version: 'v1.28.0', kernelVersion: '5.15.0-91-generic' },
  { id: 2, name: 'node-prod-02', status: 'running', cpu: 55, memory: 10.8, internalIp: '10.0.0.2', externalIp: '192.168.1.11', version: 'v1.28.0', kernelVersion: '5.15.0-91-generic' },
  { id: 3, name: 'node-prod-03', status: 'error', cpu: 0, memory: 0, internalIp: '10.0.0.3', externalIp: '192.168.1.12', version: 'v1.28.0', kernelVersion: '5.15.0-91-generic' },
];

const mockPipelinesData = [
  { id: 1, rootWebDirectory: '/var/www/html', rootStorageDirectory: '/mnt/storage', environment: 'Production', maintenanceMode: false, buildCommands: 'npm run build', company: 'Acme Corp' },
  { id: 2, rootWebDirectory: '/var/www/staging', rootStorageDirectory: '/mnt/staging-storage', environment: 'Staging', maintenanceMode: false, buildCommands: 'npm run build:staging', company: 'Beta LLC' },
  { id: 3, rootWebDirectory: '/var/www/dev', rootStorageDirectory: '/mnt/dev-storage', environment: 'Development', maintenanceMode: true, buildCommands: 'npm run dev', company: 'Gamma Design' },
];

const mockActions = [
  { id: 1, name: 'Deploy Production', company: 'Acme Corp', user: 'John Doe', duration: '2m 34s', createdAt: '2024-01-15 10:30', completedAt: '2024-01-15 10:32', status: 'completed' },
  { id: 2, name: 'Database Backup', company: 'Beta LLC', user: 'Jane Smith', duration: '5m 12s', createdAt: '2024-01-15 09:00', completedAt: '2024-01-15 09:05', status: 'completed' },
  { id: 3, name: 'Cache Clear', company: 'Gamma Design', user: 'Mike Johnson', duration: '45s', createdAt: '2024-01-15 08:15', completedAt: '2024-01-15 08:16', status: 'completed' },
  { id: 4, name: 'SSL Renewal', company: 'Acme Corp', user: 'System', duration: '1m 20s', createdAt: '2024-01-14 03:00', completedAt: null, status: 'in_progress' },
];

// Mock data for deployment dropdowns
const mockProviders = ['GitHub', 'GitLab', 'Bitbucket'];
const mockRepositories = {
  'GitHub': ['altitude/web-app', 'altitude/api-service', 'infra/terraform'],
  'GitLab': ['myproject/frontend', 'myproject/backend'],
  'Bitbucket': ['team/project-a', 'team/project-b']
};
const mockBranches = {
  'altitude/web-app': ['main', 'develop', 'staging'],
  'altitude/api-service': ['main', 'develop'],
  'infra/terraform': ['main', 'production'],
  'myproject/frontend': ['main', 'dev'],
  'myproject/backend': ['main', 'dev'],
  'team/project-a': ['master', 'develop'],
  'team/project-b': ['master']
};

const mockPipelines = ['main-pipeline', 'api-pipeline', 'frontend-pipeline', 'staging-pipeline', 'dev-pipeline'];

// Mock pipelines for Pipelines tab table - Matches: Control panel redesign images.pdf → Pipelines tab
const mockPipelinesTableData = [
  { 
    id: 1395, 
    environment: 'Production', 
    rootWebDirectory: 'var/www_m2/example.co.uk', 
    rootStorageDirectory: 'var/www_m2/example.co.uk/', 
    deploymentPlatform: 'Magento 2', 
    notes: 'Full Deployment Pipeline for Magento 2 auto generated by Altitude.', 
    maintenanceModeDuringDeployment: true, 
    customBuildCommands: true, 
    customPostBuildCommands: false 
  },
];

// Mock deployments listing data - Matches: Control panel redesign images.pdf → Deployments tab
const mockDeploymentsListing = [
  { id: 1, deploymentName: 'web-app-deploy-001', deploymentPipeline: 'main-pipeline', tasks: 5, status: 'completed', created: '2025-12-04 10:30:00', duration: '3m 24s' },
  { id: 2, deploymentName: 'api-service-deploy-042', deploymentPipeline: 'api-pipeline', tasks: 3, status: 'completed', created: '2025-12-04 09:15:00', duration: '2m 10s' },
  { id: 3, deploymentName: 'frontend-build-089', deploymentPipeline: 'frontend-pipeline', tasks: 4, status: 'failed', created: '2025-12-03 16:45:00', duration: '1m 55s' },
];

// Quick Actions list - Matches: Control panel redesign images.pdf → Quick Actions tab
const quickActionsList = [
  'Restart Web Pods',
  'Restart Database Pods',
  'Restart Redis Pods',
  'Restart RabbitMQ Pods',
  'Restart Elastic Search Pods',
  'Restart Cli',
  'Restart Varnish'
];

const TABS = [
  'General', 'Pods', 'Nodes', 'Deployments', 'Pipelines', 
  'Emails', 'Cache Warmer', 'Actions', 'Diagnostics', 
  'Autoscaler', 'Monitors', 'Quick Actions', 'Firewall'
];

export default function Environments() {
  const navigate = useNavigate();
  const location = useLocation();
  const [activeTab, setActiveTab] = useState(() => {
    // Initialize from URL query params or default to 'General'
    const params = new URLSearchParams(location.search);
    return params.get('tab') || 'General';
  });
  const [quickActionsOpen, setQuickActionsOpen] = useState(false);
  const [tabLoading, setTabLoading] = useState(false);
  
  // Environment details data with localStorage persistence
  const [envDetails] = useState({
    name: 'Production - Main Site',
    id: 'env-3029',
    ip: '192.168.1.100',
    region: 'us-east-1',
    phpVersion: '8.2',
    diskUsage: '45%',
    sslStatus: 'Active'
  });

  // Update URL when tab changes (Tab Persistence)
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    params.set('tab', activeTab);
    navigate(`${location.pathname}?${params.toString()}`, { replace: true });
  }, [activeTab, navigate, location.pathname]);
  
  // Live data state for Pods and Nodes
  const [pods, setPods] = useState(initialPods);
  const [nodes, setNodes] = useState(initialNodes);
  
  // Deployment form state with localStorage persistence
  const [deploymentHistory, setDeploymentHistory] = useState(() => {
    const saved = localStorage.getItem('deployment_history');
    return saved ? JSON.parse(saved) : [
      { id: 1, pipeline: 'main-pipeline', provider: 'GitHub', repo: 'altitude/web-app', branch: 'main', status: 'completed', progress: 100, date: '2024-01-15 10:30' },
      { id: 2, pipeline: 'staging-pipeline', provider: 'GitLab', repo: 'infra/terraform', branch: 'develop', status: 'completed', progress: 100, date: '2024-01-14 15:45' },
      { id: 3, pipeline: 'main-pipeline', provider: 'GitHub', repo: 'altitude/api-service', branch: 'main', status: 'failed', progress: 65, date: '2024-01-13 09:15' },
    ];
  });
  const [accountConnected, setAccountConnected] = useState(true);
  const [checkingAccount, setCheckingAccount] = useState(false);
  const [deploymentStep, setDeploymentStep] = useState(0);
  const [pipeline, setPipeline] = useState('');
  const [provider, setProvider] = useState('');
  const [repository, setRepository] = useState('');
  const [branch, setBranch] = useState('');
  const [deploymentProgress, setDeploymentProgress] = useState(0);
  const [isDeploying, setIsDeploying] = useState(false);

  // Deployment tasks state for Recent Deployment Tasks table
  const [deploymentTasks, setDeploymentTasks] = useState(() => {
    const saved = localStorage.getItem('deployment_tasks');
    return saved ? JSON.parse(saved) : [
      { id: 1, commitHash: '8f2d3a1', message: 'Update styles', author: 'Catherine J.', status: 'In Progress', progress: 0 },
      { id: 2, commitHash: '7b4e9c2', message: 'Fix login bug', author: 'Michael T.', status: 'Completed', progress: 100 },
      { id: 3, commitHash: '3a1f5d8', message: 'Add new feature', author: 'Sarah L.', status: 'Completed', progress: 100 },
    ];
  });
  
  // Animate progress bar for in-progress deployment task
  useEffect(() => {
    const interval = setInterval(() => {
      setDeploymentTasks(prevTasks => 
        prevTasks.map((task, index) => {
          if (index === 0 && task.status === 'In Progress' && task.progress < 100) {
            const newProgress = Math.min(100, task.progress + Math.random() * 5);
            if (newProgress >= 100) {
              return { ...task, progress: 100, status: 'Completed' };
            }
            return { ...task, progress: newProgress };
          }
          return task;
        })
      );
    }, 500);
    
    return () => clearInterval(interval);
  }, []);
  
  // Save deployment tasks to localStorage
  useEffect(() => {
    localStorage.setItem('deployment_tasks', JSON.stringify(deploymentTasks));
  }, [deploymentTasks]);
  
  // Firewall state with localStorage persistence
  const [firewallRules, setFirewallRules] = useState(() => {
    const saved = localStorage.getItem('firewall_rules');
    return saved ? JSON.parse(saved) : [
      { ip: '192.168.1.1', type: 'Allow' },
      { ip: '10.0.0.1', type: 'Allow' }
    ];
  });
  const [newIP, setNewIP] = useState('');
  const [newRuleType, setNewRuleType] = useState('Allow');
  const [copiedIP, setCopiedIP] = useState(null);
  
  // Cache Warmer state with localStorage persistence
  const [cacheUrls, setCacheUrls] = useState(() => {
    const saved = localStorage.getItem('cache_urls');
    return saved ? JSON.parse(saved) : [
      'https://example.com/',
      'https://example.com/products',
      'https://example.com/about'
    ];
  });
  const [newUrl, setNewUrl] = useState('');
  const [automaticWarming, setAutomaticWarming] = useState(true);
  const [cacheCleared, setCacheCleared] = useState(false);
  const [clearingCache, setClearingCache] = useState(false);
  
  // Autoscaler state with localStorage persistence
  const [autoscalerEnabled, setAutoscalerEnabled] = useState(() => {
    const saved = localStorage.getItem('autoscaler_enabled');
    return saved ? JSON.parse(saved) : true;
  });
  const [minReplicas, setMinReplicas] = useState(() => {
    const saved = localStorage.getItem('min_replicas');
    return saved ? parseInt(saved) : 2;
  });
  const [maxReplicas, setMaxReplicas] = useState(() => {
    const saved = localStorage.getItem('max_replicas');
    return saved ? parseInt(saved) : 10;
  });
  const [targetCPU, setTargetCPU] = useState(() => {
    const saved = localStorage.getItem('target_cpu');
    return saved ? parseInt(saved) : 70;
  });
  const [activePodsCount, setActivePodsCount] = useState(4);
  const [scalingHistory, setScalingHistory] = useState([4, 5, 4, 6, 5, 4, 5, 6, 7, 6]);
  
  // Diagnostics state
  const [diagnosticsRunning, setDiagnosticsRunning] = useState(false);
  const [diagnosticsOutput, setDiagnosticsOutput] = useState([]);
  const terminalRef = useRef(null);
  
  // Monitors state
  const [monitors] = useState({
    http: { uptime: '99.99%', status: 'healthy' },
    ping: { uptime: '99.98%', status: 'healthy' },
    ssl: { uptime: '99.99%', status: 'healthy' }
  });

  // Save firewall rules to localStorage whenever they change
  useEffect(() => {
    localStorage.setItem('firewall_rules', JSON.stringify(firewallRules));
  }, [firewallRules]);

  // Save deployment history to localStorage
  useEffect(() => {
    localStorage.setItem('deployment_history', JSON.stringify(deploymentHistory));
  }, [deploymentHistory]);

  // Save autoscaler settings to localStorage
  useEffect(() => {
    localStorage.setItem('autoscaler_enabled', JSON.stringify(autoscalerEnabled));
    localStorage.setItem('min_replicas', minReplicas.toString());
    localStorage.setItem('max_replicas', maxReplicas.toString());
    localStorage.setItem('target_cpu', targetCPU.toString());
  }, [autoscalerEnabled, minReplicas, maxReplicas, targetCPU]);

  // Save cache URLs to localStorage
  useEffect(() => {
    localStorage.setItem('cache_urls', JSON.stringify(cacheUrls));
  }, [cacheUrls]);

  // Update breadcrumb on mount and when activeTab changes - matches hierarchy: All Clients > Example Company > Website Name > [Active Tab Name]
  useEffect(() => {
    const event = new CustomEvent('breadcrumb-update', {
      detail: { company: 'Example Company', website: 'Main Website', tab: activeTab }
    });
    window.dispatchEvent(event);
  }, [activeTab]);

  // Update active pods count based on running pods
  useEffect(() => {
    const runningPods = pods.filter(pod => pod.status === 'running').length;
    setActivePodsCount(runningPods);
  }, [pods]);

  // Simulate live data fluctuations for Pods and Nodes - updates every 2 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      setPods(prevPods => prevPods.map(pod => ({
        ...pod,
        cpu: pod.status === 'running' ? Math.min(100, Math.max(0, pod.cpu + (Math.random() - 0.5) * 4)).toFixed(0) : pod.cpu,
        memory: pod.status === 'running' ? Math.max(0.1, (pod.memory + (Math.random() - 0.5) * 0.3)).toFixed(1) : pod.memory
      })));
      
      setNodes(prevNodes => prevNodes.map(node => ({
        ...node,
        cpu: node.status === 'running' ? Math.min(100, Math.max(0, node.cpu + (Math.random() - 0.5) * 4)).toFixed(0) : node.cpu,
        memory: node.status === 'running' ? Math.max(0.1, (node.memory + (Math.random() - 0.5) * 0.5)).toFixed(1) : node.memory
      })));
    }, 2000);
    
    return () => clearInterval(interval);
  }, []);

  // Simulate deployment progress
  useEffect(() => {
    if (isDeploying && deploymentProgress < 100) {
      const timer = setTimeout(() => {
        setDeploymentProgress(prev => Math.min(100, prev + Math.random() * 15));
      }, 500);
      return () => clearTimeout(timer);
    } else if (deploymentProgress >= 100) {
      setIsDeploying(false);
    }
  }, [isDeploying, deploymentProgress]);

  // IPv4 and IPv6 regex validation
  const isValidIP = (ip) => {
    const ipv4Regex = /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;
    return ipv4Regex.test(ip);
  };
  
  const canAddIP = isValidIP(newIP) && !firewallRules.some(rule => rule.ip === newIP);
  
  const handleAddIP = () => {
    if (canAddIP) {
      setFirewallRules([...firewallRules, { ip: newIP, type: newRuleType }]);
      setNewIP('');
      setNewRuleType('Allow');
    }
  };
  
  const handleRemoveIP = (ipToRemove) => {
    setFirewallRules(firewallRules.filter(rule => rule.ip !== ipToRemove));
  };

  const handleCopyIP = (ip) => {
    navigator.clipboard.writeText(ip);
    setCopiedIP(ip);
    setTimeout(() => setCopiedIP(null), 2000);
  };

  // Get current IP for firewall - auto-fills with 182.161.x.x format
  const handleAddCurrentIP = () => {
    const mockCurrentIP = '182.161.45.123';
    if (!firewallRules.some(rule => rule.ip === mockCurrentIP)) {
      setFirewallRules([...firewallRules, { ip: mockCurrentIP, type: 'Allow' }]);
    }
    setNewIP(mockCurrentIP);
  };

  // Handle clearing cache with 2 second loading
  const handleClearCache = () => {
    setClearingCache(true);
    setCacheCleared(false);
    setTimeout(() => {
      setClearingCache(false);
      setCacheCleared(true);
      setTimeout(() => setCacheCleared(false), 3000);
    }, 2000);
  };

  // Handle adding URL to cache warmer
  const handleAddUrl = () => {
    if (newUrl && !cacheUrls.includes(newUrl)) {
      setCacheUrls([...cacheUrls, newUrl]);
      setNewUrl('');
    }
  };

  // Handle removing URL from cache warmer
  const handleRemoveUrl = (urlToRemove) => {
    setCacheUrls(cacheUrls.filter(url => url !== urlToRemove));
  };

  // Handle running diagnostics with typed output - terminal experience with timestamps and auto-scroll
  const handleRunDiagnostics = () => {
    setDiagnosticsRunning(true);
    setDiagnosticsOutput([]);
    
    const getCurrentTime = () => {
      const now = new Date();
      return now.toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
    };

    const steps = [
      { text: `[${getCurrentTime()}] INFO: Starting diagnostics...`, result: '', delay: 400 },
      { text: `[${getCurrentTime()}] INFO: Verifying SSL certificate...`, result: 'Valid for 89 days', delay: 1000 },
      { text: `[${getCurrentTime()}] INFO: Checking database connection...`, result: 'OK (latency: 3ms)', delay: 1600 },
      { text: `[${getCurrentTime()}] INFO: Testing API endpoints...`, result: 'All healthy', delay: 2200 },
      { text: `[${getCurrentTime()}] INFO: Network latency check...`, result: '14ms avg', delay: 2800 },
      { text: `[${getCurrentTime()}] SUCCESS: Diagnostics completed successfully.`, result: '', delay: 3200 },
    ];
    
    steps.forEach((step, index) => {
      setTimeout(() => {
        setDiagnosticsOutput(prev => [...prev, { text: step.text, result: step.result }]);
        if (index === steps.length - 1) {
          setDiagnosticsRunning(false);
        }
      }, step.delay);
    });
  };

  // Auto-scroll terminal to bottom when new output arrives
  useEffect(() => {
    if (terminalRef.current) {
      terminalRef.current.scrollTop = terminalRef.current.scrollHeight;
    }
  }, [diagnosticsOutput]);

  // Simulate scaling history updates for the graph
  useEffect(() => {
    if (autoscalerEnabled) {
      const interval = setInterval(() => {
        setScalingHistory(prev => {
          const newCount = Math.max(minReplicas, Math.min(maxReplicas, prev[prev.length - 1] + (Math.random() > 0.5 ? 1 : -1)));
          return [...prev.slice(1), newCount];
        });
      }, 2000);
      return () => clearInterval(interval);
    }
  }, [autoscalerEnabled, minReplicas, maxReplicas]);
  
  // Check if all deployment fields are filled
  const canSaveDeployment = pipeline && provider && repository && branch;
  
  // Get available repositories based on selected provider
  const getAvailableRepositories = () => {
    if (!provider) return [];
    return mockRepositories[provider] || [];
  };
  
  // Get available branches based on selected repository
  const getAvailableBranches = () => {
    if (!repository) return [];
    return mockBranches[repository] || [];
  };
  
  // Handle provider selection - simulate account check
  const handleProviderChange = (newProvider) => {
    setProvider(newProvider);
    setRepository('');
    setBranch('');
    setDeploymentStep(1);
    setCheckingAccount(true);
    setAccountConnected(false);
    
    // Simulate checking for accounts
    setTimeout(() => {
      setCheckingAccount(false);
      // Randomly decide if account is connected (for demo purposes, always false)
      setAccountConnected(false);
    }, 1500);
  };
  
  // Handle repository selection - reset branch
  const handleRepositoryChange = (repo) => {
    setRepository(repo);
    setDeploymentStep(2);
    setBranch('');
  };

  // Handle pipeline selection
  const handlePipelineChange = (newPipeline) => {
    setPipeline(newPipeline);
    setDeploymentStep(1);
    setProvider('');
    setRepository('');
    setBranch('');
  };

  // Handle branch selection
  const handleBranchChange = (newBranch) => {
    setBranch(newBranch);
    setDeploymentStep(3);
  };

  const handleDeploy = () => {
    if (canSaveDeployment) {
      setIsDeploying(true);
      setDeploymentProgress(0);
    }
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case 'General':
        return (
          <div className="p-6">
            <div className="grid grid-cols-2 gap-6">
              {/* Left Column - Environment Details */}
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <h3 className="text-sm font-semibold text-gray-700 mb-4 flex items-center gap-2">
                  <Server className="w-4 h-4" />
                  Environment Details
                </h3>
                <div className="space-y-3">
                  <div>
                    <label className="text-xs text-gray-500 uppercase">Name</label>
                    <OrangeLink href="#" className="block font-medium text-sm">{envDetails.name}</OrangeLink>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase">ID</label>
                    <div className="flex items-center gap-2">
                      <OrangeLink href="#" className="font-mono text-sm">{envDetails.id}</OrangeLink>
                      <button onClick={() => { navigator.clipboard.writeText(envDetails.id); }} className="text-gray-400 hover:text-gray-600">
                        <Copy className="w-3 h-3" />
                      </button>
                    </div>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase">IP Address</label>
                    <div className="flex items-center gap-2">
                      <OrangeLink href="#" className="font-mono text-sm">{envDetails.ip}</OrangeLink>
                      <button onClick={() => { navigator.clipboard.writeText(envDetails.ip); }} className="text-gray-400 hover:text-gray-600">
                        <Copy className="w-3 h-3" />
                      </button>
                    </div>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase">Region</label>
                    <div className="flex items-center gap-2">
                      <MapPin className="w-3 h-3 text-gray-400" />
                      <OrangeLink href="#" className="font-medium text-sm">{envDetails.region}</OrangeLink>
                    </div>
                  </div>
                </div>
              </div>
              
              {/* Right Column - Technical Specs */}
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <h3 className="text-sm font-semibold text-gray-700 mb-4 flex items-center gap-2">
                  <Cpu className="w-4 h-4" />
                  Technical Specifications
                </h3>
                <div className="space-y-3">
                  <div>
                    <label className="text-xs text-gray-500 uppercase">PHP Version</label>
                    <p className="font-mono text-sm text-gray-900">{envDetails.phpVersion}</p>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase">Disk Usage</label>
                    <div className="flex items-center gap-2">
                      <HardDrive className="w-3 h-3 text-gray-400" />
                      <p className="font-mono text-sm text-gray-900">{envDetails.diskUsage}</p>
                    </div>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase">SSL Status</label>
                    <div className="flex items-center gap-2">
                      <Shield className="w-3 h-3 text-green-500" />
                      <p className="font-medium text-sm text-green-700">{envDetails.sslStatus}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'Pods':
        return (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Pod Name</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Status</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">CPU %</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Memory</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Node Type</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">IP</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Age</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Containers</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Restarts</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Ready</th>
                </tr>
              </thead>
              <tbody>
                {pods.map((pod) => (
                  <tr key={`pod-${pod.id}`} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                    <td className="py-2 px-3">
                      <OrangeLink href="#" className="font-mono text-sm">{pod.name}</OrangeLink>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <span className={`w-2 h-2 rounded-full ${pod.status === 'running' ? 'bg-green-500 animate-pulse' : pod.status === 'error' ? 'bg-red-500' : 'bg-yellow-500 animate-pulse'}`}></span>
                        <span className="text-gray-700 capitalize">{pod.status}</span>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <div className="w-16 bg-gray-200 rounded-full h-1.5">
                          <div className="bg-brand-orange h-1.5 rounded-full" style={{ width: `${pod.cpu}%` }}></div>
                        </div>
                        <span className="font-mono text-xs text-gray-600">{pod.cpu}%</span>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <MemoryStick className="w-3 h-3 text-gray-400" />
                        <span className="font-mono text-xs text-gray-600">{pod.memory}GB</span>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      <span className="text-xs px-2 py-1 rounded bg-blue-100 text-blue-800">{pod.nodeType}</span>
                    </td>
                    <td className="py-2 px-3 font-mono text-xs text-gray-600">{pod.ip}</td>
                    <td className="py-2 px-3 text-gray-600">{pod.age}</td>
                    <td className="py-2 px-3 font-mono text-xs text-gray-600">{pod.containers}</td>
                    <td className="py-2 px-3 text-gray-600">{pod.restarts}</td>
                    <td className="py-2 px-3">
                      <span className={`text-xs px-2 py-1 rounded ${pod.ready ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                        {pod.ready ? 'Yes' : 'No'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );

      case 'Nodes':
        return (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Node Name</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Status</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">CPU %</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Memory</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Internal IP</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">External IP</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Version</th>
                  <th className="text-left py-2 px-3 font-semibold text-gray-700">Kernel Version</th>
                </tr>
              </thead>
              <tbody>
                {nodes.map((node) => (
                  <tr key={`node-${node.id}`} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                    <td className="py-2 px-3">
                      <OrangeLink href="#" className="font-mono text-sm">{node.name}</OrangeLink>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <span className={`w-2 h-2 rounded-full ${node.status === 'running' ? 'bg-green-500 animate-pulse' : node.status === 'error' ? 'bg-red-500' : 'bg-yellow-500 animate-pulse'}`}></span>
                        <span className="text-gray-700 capitalize">{node.status}</span>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <div className="w-16 bg-gray-200 rounded-full h-1.5">
                          <div className="bg-brand-orange h-1.5 rounded-full" style={{ width: `${node.cpu}%` }}></div>
                        </div>
                        <span className="font-mono text-xs text-gray-600">{node.cpu}%</span>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <MemoryStick className="w-3 h-3 text-gray-400" />
                        <span className="font-mono text-xs text-gray-600">{node.memory}GB</span>
                      </div>
                    </td>
                    <td className="py-2 px-3 font-mono text-xs text-gray-600">{node.internalIp}</td>
                    <td className="py-2 px-3 font-mono text-xs text-gray-600">{node.externalIp}</td>
                    <td className="py-2 px-3 font-mono text-xs text-gray-600">{node.version}</td>
                    <td className="py-2 px-3 text-gray-600">{node.kernelVersion}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      
      case 'Deployments':
        return (
          <div className="p-4">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Add New Repository</h3>
            
            {/* Deployment Progress Timeline */}
            {isDeploying && (
              <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <h4 className="font-medium text-blue-900 mb-3">Deployment in Progress</h4>
                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${deploymentProgress >= 25 ? 'bg-green-500' : 'bg-gray-300'}`}>
                      {deploymentProgress >= 25 ? <Check className="w-4 h-4 text-white" /> : <div className="w-2 h-2 bg-white rounded-full" />}
                    </div>
                    <span className="text-sm text-gray-700">Initializing</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${deploymentProgress >= 50 ? 'bg-green-500' : 'bg-gray-300'}`}>
                      {deploymentProgress >= 50 ? <Check className="w-4 h-4 text-white" /> : <div className="w-2 h-2 bg-white rounded-full" />}
                    </div>
                    <span className="text-sm text-gray-700">Building</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${deploymentProgress >= 75 ? 'bg-green-500' : 'bg-gray-300'}`}>
                      {deploymentProgress >= 75 ? <Check className="w-4 h-4 text-white" /> : <div className="w-2 h-2 bg-white rounded-full" />}
                    </div>
                    <span className="text-sm text-gray-700">Deploying</span>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${deploymentProgress >= 100 ? 'bg-green-500' : 'bg-gray-300'}`}>
                      {deploymentProgress >= 100 ? <Check className="w-4 h-4 text-white" /> : <div className="w-2 h-2 bg-white rounded-full" />}
                    </div>
                    <span className="text-sm text-gray-700">Complete</span>
                  </div>
                </div>
                <div className="mt-4">
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div 
                      className="bg-brand-orange h-2 rounded-full transition-all duration-500"
                      style={{ width: `${deploymentProgress}%` }}
                    />
                  </div>
                  <p className="text-xs text-gray-500 mt-1">{deploymentProgress.toFixed(0)}% complete</p>
                </div>
              </div>
            )}
            
            {checkingAccount && (
              <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded-lg flex items-center gap-3">
                <Loader2 className="w-5 h-5 text-blue-600 animate-spin" />
                <span className="text-blue-800 font-medium">Checking for accounts...</span>
              </div>
            )}
            
            {!accountConnected && !checkingAccount && provider === 'GitHub' && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-center gap-3">
                <AlertTriangle className="w-5 h-5 text-red-600" />
                <span className="text-red-800 font-medium">
                  ⚠️ No account connected. <OrangeLink href="#" className="font-semibold">Link GitHub Account</OrangeLink>
                </span>
              </div>
            )}
            
            {!accountConnected && !checkingAccount && provider !== 'GitHub' && provider && (
              <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg flex items-center gap-3">
                <AlertTriangle className="w-5 h-5 text-yellow-600" />
                <span className="text-yellow-800 font-medium">⚠️ No account connected. Please link a provider in Settings.</span>
              </div>
            )}
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 max-w-4xl">
              {/* Pipeline Dropdown */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Pipeline</label>
                <div className="relative">
                  <select
                    value={pipeline}
                    onChange={(e) => handlePipelineChange(e.target.value)}
                    disabled={checkingAccount}
                    className={`w-full px-3 py-2 border border-gray-300 rounded-md appearance-none bg-white pr-10
                      ${checkingAccount ? 'bg-gray-100 cursor-not-allowed text-gray-400' : 'cursor-pointer hover:border-gray-400'}
                      focus:outline-none focus:ring-2 focus:ring-brand-orange focus:border-transparent`}
                  >
                    <option value="">Select Pipeline</option>
                    {mockPipelines.map(pipelineOption => (
                      <option key={pipelineOption} value={pipelineOption}>{pipelineOption}</option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
              </div>
              
              {/* Provider Dropdown - disabled if no pipeline selected */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Provider</label>
                <div className="relative">
                  <select
                    value={provider}
                    onChange={(e) => handleProviderChange(e.target.value)}
                    disabled={!pipeline || checkingAccount}
                    className={`w-full px-3 py-2 border border-gray-300 rounded-md appearance-none bg-white pr-10
                      ${(!pipeline || checkingAccount) ? 'bg-gray-100 cursor-not-allowed text-gray-400' : 'cursor-pointer hover:border-gray-400'}
                      focus:outline-none focus:ring-2 focus:ring-brand-orange focus:border-transparent`}
                  >
                    <option value="">Select Provider</option>
                    {mockProviders.map(providerOption => (
                      <option key={providerOption} value={providerOption}>{providerOption}</option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
              </div>
              
              {/* Repository Dropdown - disabled if no provider selected */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Repository</label>
                <div className="relative">
                  <select
                    value={repository}
                    onChange={(e) => handleRepositoryChange(e.target.value)}
                    disabled={!provider || checkingAccount}
                    className={`w-full px-3 py-2 border border-gray-300 rounded-md appearance-none bg-white pr-10
                      ${(!provider || checkingAccount) ? 'bg-gray-100 cursor-not-allowed text-gray-400' : 'cursor-pointer hover:border-gray-400'}
                      focus:outline-none focus:ring-2 focus:ring-brand-orange focus:border-transparent`}
                  >
                    <option value="">Select Repository</option>
                    {getAvailableRepositories().map(repo => (
                      <option key={repo} value={repo}>{repo}</option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
              </div>
              
              {/* Branch Dropdown - disabled if no repository selected */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Branch</label>
                <div className="relative">
                  <select
                    value={branch}
                    onChange={(e) => handleBranchChange(e.target.value)}
                    disabled={!repository || checkingAccount}
                    className={`w-full px-3 py-2 border border-gray-300 rounded-md appearance-none bg-white pr-10
                      ${(!repository || checkingAccount) ? 'bg-gray-100 cursor-not-allowed text-gray-400' : 'cursor-pointer hover:border-gray-400'}
                      focus:outline-none focus:ring-2 focus:ring-brand-orange focus:border-transparent`}
                  >
                    <option value="">Select Branch</option>
                    {getAvailableBranches().map(branchOption => (
                      <option key={branchOption} value={branchOption}>{branchOption}</option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" />
                </div>
              </div>
            </div>
            
            <div className="mt-6">
              <button
                onClick={handleDeploy}
                disabled={!canSaveDeployment || isDeploying}
                className={`px-6 py-2 rounded-md font-medium transition-all flex items-center gap-2
                  ${(canSaveDeployment && !isDeploying) 
                    ? 'bg-brand-orange text-white hover:bg-orange-600 shadow-sm' 
                    : 'bg-gray-200 text-gray-400 cursor-not-allowed'}`}
              >
                {isDeploying ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Deploying...
                  </>
                ) : (
                  'Deploy'
                )}
              </button>
            </div>

            {/* Configuration Block - Matches: Control panel redesign images.pdf → Deployments tab */}
            <div className="mt-8 bg-gray-50 rounded-lg p-4 border border-gray-200">
              <h4 className="text-md font-semibold text-gray-900 mb-4">Configuration Block</h4>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Deployment Pipeline Status</label>
                  <select className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange">
                    <option value="enabled">Enabled</option>
                    <option value="disabled">Disabled</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Git Repositories</label>
                  <input
                    type="text"
                    placeholder="0"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Deployment Type</label>
                  <select className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange">
                    <option value="automatic">Automatic Deployment</option>
                    <option value="manual">Manual</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Pipeline Shared Storage</label>
                  <select className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange">
                    <option value="enabled">Enabled</option>
                    <option value="disabled">Disabled</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Shared Var Folder / Using Shared Env</label>
                  <select disabled className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm bg-gray-100 text-gray-400 cursor-not-allowed">
                    <option value="disabled">Disabled</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Slack Channel</label>
                  <input
                    type="text"
                    defaultValue="Use Default"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Build Server IP</label>
                  <input
                    type="text"
                    placeholder="Auto detect from cluster"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange"
                  />
                </div>
                <div>
                  <label className="block text-xs text-gray-500 uppercase mb-1">Deployment Method Configuration</label>
                  <select className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange">
                    <option value="docker">From Global Config (Docker)</option>
                    <option value="legacy">From Global Config (Legacy)</option>
                    <option value="base">From Global Config (Base)</option>
                  </select>
                </div>
              </div>
            </div>

            {/* Deployments Listing Table - Matches: Control panel redesign images.pdf → Deployments tab */}
            <div className="mt-8">
              <div className="flex items-center justify-between mb-4">
                <input
                  type="text"
                  placeholder="Search deployments..."
                  className="px-4 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange w-64"
                />
                <div className="flex items-center gap-2">
                  <button className="px-4 py-2 bg-brand-orange text-white rounded-md text-sm font-medium hover:bg-orange-600 transition-colors">
                    Create Deployment
                  </button>
                  <select className="px-4 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange">
                    <option value="">Select Action</option>
                    <option value="retry">Retry Selected</option>
                    <option value="rollback">Rollback Selected</option>
                    <option value="delete">Delete Selected</option>
                  </select>
                </div>
              </div>
              
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-200 bg-gray-50">
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">
                        <input type="checkbox" className="rounded border-gray-300 text-brand-orange focus:ring-brand-orange" />
                      </th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">DEPLOYMENT NAME</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">DEPLOYMENT PIPELINE</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">TASKS</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">STATUS</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">CREATED</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">DURATION</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                    {mockDeploymentsListing.map((deployment) => (
                      <tr key={`deployment-${deployment.id}`} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                        <td className="py-3 px-4">
                          <input type="checkbox" className="rounded border-gray-300 text-brand-orange focus:ring-brand-orange" />
                        </td>
                        <td className="py-3 px-4 font-mono text-xs text-gray-600">{deployment.deploymentName}</td>
                        <td className="py-3 px-4 font-mono text-xs text-gray-600">{deployment.deploymentPipeline}</td>
                        <td className="py-3 px-4 text-gray-700">{deployment.tasks}</td>
                        <td className="py-3 px-4">
                          <span className={`text-xs px-2 py-1 rounded ${deployment.status === 'completed' ? 'bg-green-100 text-green-800' : deployment.status === 'failed' ? 'bg-red-100 text-red-800' : 'bg-blue-100 text-blue-800'}`}>
                            {deployment.status === 'completed' ? 'Completed' : deployment.status === 'failed' ? 'Failed' : 'In Progress'}
                          </span>
                        </td>
                        <td className="py-3 px-4 font-mono text-xs text-gray-600">{deployment.created}</td>
                        <td className="py-3 px-4 font-mono text-xs text-gray-600">{deployment.duration}</td>
                        <td className="py-3 px-4">
                          <div className="flex items-center gap-2">
                            <button className="text-xs px-2 py-1 bg-blue-100 text-blue-800 rounded hover:bg-blue-200 transition-colors" title="Retry">
                              Retry
                            </button>
                            <button className="text-xs px-2 py-1 bg-yellow-100 text-yellow-800 rounded hover:bg-yellow-200 transition-colors" title="Rollback">
                              Rollback
                            </button>
                            <button className="text-xs px-2 py-1 bg-gray-100 text-gray-800 rounded hover:bg-gray-200 transition-colors" title="View">
                              View
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Recent Deployment Tasks Table */}
            <div className="mt-8">
              <h4 className="text-md font-semibold text-gray-900 mb-4">Recent Deployment Tasks</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-200 bg-gray-50">
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">Commit Hash</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">Message</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">Author</th>
                      <th className="text-left py-3 px-4 font-semibold text-gray-700">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {/* Top Row - In Progress with pulsing green dot and animated progress bar */}
                    {deploymentTasks.map((task, index) => (
                      <tr key={task.id} className={`border-b border-gray-100 hover:bg-gray-50 transition-colors ${index === 0 ? 'bg-green-50' : ''}`}>
                        <td className="py-3 px-4">
                          <code className="font-mono text-xs bg-gray-100 px-2 py-1 rounded">{task.commitHash}</code>
                        </td>
                        <td className="py-3 px-4 text-gray-700">{task.message}</td>
                        <td className="py-3 px-4 text-gray-700">{task.author}</td>
                        <td className="py-3 px-4">
                          {task.status === 'In Progress' ? (
                            <div className="flex items-center gap-3">
                              <div className="flex items-center gap-2">
                                <span className="relative flex h-3 w-3">
                                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                                  <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500"></span>
                                </span>
                                <span className="text-green-700 font-medium">In Progress</span>
                              </div>
                              <div className="w-24 bg-gray-200 rounded-full h-1.5">
                                <div 
                                  className="bg-brand-orange h-1.5 rounded-full transition-all duration-300"
                                  style={{ width: `${task.progress}%` }}
                                />
                              </div>
                              <span className="text-xs text-gray-500">{task.progress.toFixed(0)}%</span>
                            </div>
                          ) : (
                            <span className={`text-xs px-2 py-1 rounded ${task.status === 'Completed' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                              {task.status}
                            </span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        );
      
      // Matches: Control panel redesign images.pdf → Pipelines tab
      case 'Pipelines':
        return (
          <div className="p-4">
            {/* Header controls */}
            <div className="flex items-center justify-between mb-6">
              <input
                type="text"
                placeholder="Search pipelines..."
                className="px-4 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange w-64"
              />
              <button className="px-4 py-2 bg-brand-orange text-white rounded-md text-sm font-medium hover:bg-orange-600 transition-colors">
                Create Environment Deployment Pipeline
              </button>
            </div>
            
            {/* Pipelines Table - Matches doc columns exactly */}
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200 bg-gray-50">
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">ID</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">ENVIRONMENT</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">ROOT WEB DIRECTORY</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">ROOT STORAGE DIRECTORY</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">DEPLOYMENT PLATFORM</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">NOTES</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">MAINTENANCE MODE DURING DEPLOYMENT</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">CUSTOM BUILD COMMANDS</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">CUSTOM POST BUILD COMMANDS</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">VIEW</th>
                  </tr>
                </thead>
                <tbody>
                  {mockPipelinesTableData.map((pipeline) => (
                    <tr 
                      key={`pipeline-${pipeline.id}`} 
                      className="border-b border-gray-100 hover:bg-gray-50 transition-colors cursor-pointer"
                      onClick={() => navigate(`/environment-pipeline/${pipeline.id}`)}
                    >
                      <td className="py-3 px-4 font-mono text-xs text-gray-600">{pipeline.id}</td>
                      <td className="py-3 px-4">
                        <span className="text-xs px-2 py-1 rounded bg-blue-100 text-blue-800">{pipeline.environment}</span>
                      </td>
                      <td className="py-3 px-4 font-mono text-xs text-gray-600">{pipeline.rootWebDirectory}</td>
                      <td className="py-3 px-4 font-mono text-xs text-gray-600">{pipeline.rootStorageDirectory}</td>
                      <td className="py-3 px-4 text-gray-700">{pipeline.deploymentPlatform}</td>
                      <td className="py-3 px-4 text-gray-700 max-w-xs truncate">{pipeline.notes}</td>
                      <td className="py-3 px-4">
                        <span className={`text-xs px-2 py-1 rounded ${pipeline.maintenanceModeDuringDeployment ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800'}`}>
                          {pipeline.maintenanceModeDuringDeployment ? 'Yes' : 'No'}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        <span className={`text-xs px-2 py-1 rounded ${pipeline.customBuildCommands ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                          {pipeline.customBuildCommands ? 'Yes' : 'No'}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        <span className={`text-xs px-2 py-1 rounded ${pipeline.customPostBuildCommands ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                          {pipeline.customPostBuildCommands ? 'Yes' : 'No'}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        <button 
                          className="text-gray-400 hover:text-brand-orange transition-colors" 
                          title="View Pipeline"
                          onClick={(e) => {
                            e.stopPropagation();
                            navigate(`/environment-pipeline/${pipeline.id}`);
                          }}
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        );
      
      // Matches: Control panel redesign images.pdf → Emails tab
      case 'Emails':
        return (
          <div className="p-4 space-y-6">
            {/* Section 1: SMTP Details */}
            <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
              <h3 className="text-sm font-semibold text-gray-700 mb-3">SMTP Details</h3>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-gray-500 uppercase">Transactional Emails</label>
                  <p className="font-medium text-sm text-gray-900 mt-1">Pending setup</p>
                </div>
              </div>
            </div>
            
            {/* Section 2: Outgoing emails */}
            <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
              <h3 className="text-sm font-semibold text-gray-700 mb-3">Outgoing Emails</h3>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-gray-500 uppercase">Default outgoing email address</label>
                  <input
                    type="email"
                    defaultValue="sales@manage.altitude.com"
                    className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange"
                  />
                </div>
              </div>
            </div>
          </div>
        );
      
      // Matches: Control panel redesign images.pdf → Actions tab
      case 'Actions':
        return (
          <div className="p-4">
            {/* Header controls */}
            <div className="flex items-center justify-between mb-6">
              <input
                type="text"
                placeholder="Search actions..."
                className="px-4 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange w-64"
              />
              <div className="flex items-center gap-2">
                <button className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors">
                  Previous
                </button>
                <span className="text-sm text-gray-600">Page 1 of 3</span>
                <button className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors">
                  Next
                </button>
              </div>
            </div>
            
            {/* Actions Table - Matches doc columns exactly */}
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200 bg-gray-50">
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">NAME</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">COMPANY</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">USER</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">DURATION</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">CREATED AT</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">COMPLETED AT</th>
                    <th className="text-left py-3 px-4 font-semibold text-gray-700">STATUS</th>
                  </tr>
                </thead>
                <tbody>
                  {/* Example row from spec */}
                  <tr className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                    <td className="py-3 px-4 text-gray-700">Environment Firewall Update</td>
                    <td className="py-3 px-4 text-gray-700">Test company 123</td>
                    <td className="py-3 px-4 text-gray-700">Pemith Fonseka</td>
                    <td className="py-3 px-4 font-mono text-xs text-gray-600">6s</td>
                    <td className="py-3 px-4 font-mono text-xs text-gray-600">2025-12-04 11:43:28</td>
                    <td className="py-3 px-4 font-mono text-xs text-gray-600">2025-12-04 11:43:34</td>
                    <td className="py-3 px-4">
                      <span className="text-xs px-2 py-1 rounded bg-green-100 text-green-800">Finished</span>
                    </td>
                  </tr>
                  {/* Additional mock rows */}
                  {mockActions.map((action) => (
                    <tr key={`action-${action.id}`} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                      <td className="py-3 px-4 text-gray-700">{action.name}</td>
                      <td className="py-3 px-4 text-gray-700">{action.company}</td>
                      <td className="py-3 px-4 text-gray-700">{action.user}</td>
                      <td className="py-3 px-4 font-mono text-xs text-gray-600">{action.duration}</td>
                      <td className="py-3 px-4 font-mono text-xs text-gray-600">{action.createdAt}</td>
                      <td className="py-3 px-4 font-mono text-xs text-gray-600">{action.completedAt || '-'}</td>
                      <td className="py-3 px-4">
                        <span className={`text-xs px-2 py-1 rounded ${action.status === 'completed' ? 'bg-green-100 text-green-800' : action.status === 'in_progress' ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800'}`}>
                          {action.status === 'completed' ? 'Finished' : action.status === 'in_progress' ? 'In Progress' : action.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        );
      
      // Matches: Control panel redesign images.pdf → Quick Actions tab
      case 'Quick Actions':
        return (
          <div className="p-4">
            <div className="space-y-3">
              {quickActionsList.map((action, index) => (
                <div key={index} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-200">
                  <span className="font-medium text-gray-900">{action}</span>
                  <button className="px-4 py-2 bg-brand-orange text-white rounded-md text-sm font-medium hover:bg-orange-600 transition-colors">
                    Run
                  </button>
                </div>
              ))}
            </div>
          </div>
        );
      
      // Matches: Control panel redesign images.docx → Notifications tab (explicitly states no UI needed)
      case 'Notifications':
        return null;

      // Matches: Control panel redesign images.pdf → Firewall tab
      case 'Firewall':
        return (
          <div className="p-4">
            <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-sm text-blue-800 font-medium">Only IPv4 addresses are supported at this time.</p>
            </div>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">Firewall Rules</h3>
              <button
                onClick={handleAddCurrentIP}
                className="px-4 py-2 bg-brand-orange text-white rounded-md text-sm font-medium hover:bg-orange-600 transition-colors flex items-center gap-2"
              >
                <Shield className="w-4 h-4" />
                Use My Current IP
              </button>
            </div>
            
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200 bg-gray-50">
                    <th className="text-left py-2 px-3 font-semibold text-gray-700">IP Address</th>
                    <th className="text-left py-2 px-3 font-semibold text-gray-700">Rule Type</th>
                    <th className="text-right py-2 px-3 font-semibold text-gray-700">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {firewallRules.map((rule) => (
                    <tr key={rule.ip} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                      <td className="py-2 px-3">
                        <div className="flex items-center gap-2">
                          <OrangeLink href="#" className="font-mono text-sm">{rule.ip}</OrangeLink>
                          <button
                            onClick={() => handleCopyIP(rule.ip)}
                            className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
                            title="Copy to clipboard"
                          >
                            {copiedIP === rule.ip ? (
                              <Check className="w-4 h-4 text-green-600" />
                            ) : (
                              <Copy className="w-4 h-4" />
                            )}
                          </button>
                        </div>
                      </td>
                      <td className="py-2 px-3">
                        <span className={`text-xs px-2 py-1 rounded ${rule.type === 'Allow' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                          {rule.type}
                        </span>
                      </td>
                      <td className="py-2 px-3 text-right">
                        <button
                          onClick={() => handleRemoveIP(rule.ip)}
                          className="text-red-600 hover:text-red-800 transition-colors p-1"
                          title="Remove Rule"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </td>
                    </tr>
                  ))}
                  
                  <tr className="border-b border-gray-100 bg-gray-50">
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        <input
                          type="text"
                          value={newIP}
                          onChange={(e) => setNewIP(e.target.value)}
                          placeholder="Enter IPv4 address"
                          className={`w-full px-3 py-2 border rounded-md font-mono text-sm
                            ${isValidIP(newIP) || newIP === '' ? 'border-gray-300' : 'border-red-300 focus:border-red-500'}
                            focus:outline-none focus:ring-2 focus:ring-brand-orange`}
                        />
                        <button
                          onClick={handleAddCurrentIP}
                          className="px-3 py-2 bg-gray-200 hover:bg-gray-300 rounded-md text-sm font-medium text-gray-700 transition-colors whitespace-nowrap"
                          title="Use My Current IP"
                        >
                          Use My Current IP
                        </button>
                      </div>
                    </td>
                    <td className="py-2 px-3">
                      <select
                        value={newRuleType}
                        onChange={(e) => setNewRuleType(e.target.value)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-brand-orange"
                      >
                        <option value="Allow">Allow</option>
                        <option value="Deny">Deny</option>
                      </select>
                    </td>
                    <td className="py-2 px-3 text-right">
                      <button
                        onClick={handleAddIP}
                        disabled={!canAddIP}
                        className={`p-2 rounded-md transition-all
                          ${canAddIP 
                            ? 'bg-brand-orange text-white hover:bg-orange-600' 
                            : 'bg-gray-200 text-gray-400 cursor-not-allowed'}`}
                        title="Add Rule"
                      >
                        <Plus className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        );
      
      case 'Autoscaler':
        return (
          <div className="p-4 space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Horizontal Pod Autoscaler</h3>
                <p className="text-sm text-gray-600">Automatically scale your application based on CPU usage</p>
              </div>
              <button
                onClick={() => setAutoscalerEnabled(!autoscalerEnabled)}
                className={`flex items-center gap-2 px-4 py-2 rounded-md font-medium transition-colors ${
                  autoscalerEnabled 
                    ? 'bg-green-100 text-green-800' 
                    : 'bg-gray-100 text-gray-600'
                }`}
              >
                {autoscalerEnabled ? <ToggleRight className="w-6 h-6" /> : <ToggleLeft className="w-6 h-6" />}
                {autoscalerEnabled ? 'Enabled' : 'Disabled'}
              </button>
            </div>
            
            {/* Graph Navigation Tabs */}
            <div className="flex gap-2 border-b border-gray-200">
              <button className="px-4 py-2 text-sm font-medium text-brand-orange border-b-2 border-brand-orange">
                Hour
              </button>
              <button className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900">
                Day
              </button>
              <button className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900">
                Week
              </button>
              <button className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900">
                Month
              </button>
            </div>
            
            {/* Live Active Pods Count - Current Load Indicator */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-blue-800">
                  <Container className="w-5 h-5" />
                  <span className="font-medium">Current Load: <strong>{activePodsCount} pods active</strong></span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-sm text-gray-600">Min: {minReplicas}</span>
                  <span className="text-gray-300">|</span>
                  <span className="text-sm text-gray-600">Max: {maxReplicas}</span>
                </div>
              </div>
              <div className="mt-3 w-full bg-gray-200 rounded-full h-2">
                <div 
                  className="bg-brand-orange h-2 rounded-full transition-all duration-500"
                  style={{ width: `${Math.min(100, (activePodsCount / maxReplicas) * 100)}%` }}
                ></div>
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <label className="block text-sm font-medium text-gray-700 mb-2">Min Pods: {minReplicas}</label>
                <input
                  type="range"
                  min="1"
                  max="5"
                  value={minReplicas}
                  onChange={(e) => setMinReplicas(Math.min(parseInt(e.target.value), maxReplicas - 1))}
                  disabled={!autoscalerEnabled}
                  className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-brand-orange"
                />
              </div>
              
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <label className="block text-sm font-medium text-gray-700 mb-2">Max Pods: {maxReplicas}</label>
                <input
                  type="range"
                  min="3"
                  max="20"
                  value={maxReplicas}
                  onChange={(e) => setMaxReplicas(Math.max(parseInt(e.target.value), minReplicas + 1))}
                  disabled={!autoscalerEnabled}
                  className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-brand-orange"
                />
              </div>
              
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <label className="block text-sm font-medium text-gray-700 mb-2">Target CPU: {targetCPU}%</label>
                <input
                  type="range"
                  min="10"
                  max="90"
                  value={targetCPU}
                  onChange={(e) => setTargetCPU(parseInt(e.target.value))}
                  disabled={!autoscalerEnabled}
                  className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-brand-orange"
                />
              </div>
            </div>
            
            {autoscalerEnabled && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-center gap-2 text-green-800">
                  <Activity className="w-5 h-5" />
                  <span className="font-medium">Autoscaler is active and monitoring pod metrics</span>
                </div>
              </div>
            )}
          </div>
        );
      
      case 'Monitors':
        return (
          <div className="p-4 space-y-4">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Monitoring Configuration</h3>
            <div className="space-y-3">
              {[
                { key: 'uptime', label: 'Uptime Monitoring', desc: 'Alert when service is unreachable', icon: Activity },
                { key: 'performance', label: 'Performance Metrics', desc: 'Track response times and throughput', icon: Zap },
                { key: 'errors', label: 'Error Tracking', desc: 'Monitor application errors and exceptions', icon: AlertTriangle },
                { key: 'logs', label: 'Log Aggregation', desc: 'Collect and analyze application logs', icon: Server },
                { key: 'security', label: 'Security Scanning', desc: 'Detect vulnerabilities and threats', icon: Shield }
              ].map(({ key, label, desc, icon: Icon }) => (
                <div key={key} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-200">
                  <div className="flex items-center gap-3">
                    <Icon className={`w-5 h-5 ${monitors[key] ? 'text-brand-orange' : 'text-gray-400'}`} />
                    <div>
                      <p className="font-medium text-gray-900">{label}</p>
                      <p className="text-sm text-gray-600">{desc}</p>
                    </div>
                  </div>
                  <button
                    onClick={() => setMonitors({ ...monitors, [key]: !monitors[key] })}
                    className={`flex items-center gap-2 px-3 py-1.5 rounded-md font-medium transition-colors ${
                      monitors[key] 
                        ? 'bg-green-100 text-green-800' 
                        : 'bg-gray-200 text-gray-600'
                    }`}
                  >
                    {monitors[key] ? <ToggleRight className="w-5 h-5" /> : <ToggleLeft className="w-5 h-5" />}
                    {monitors[key] ? 'On' : 'Off'}
                  </button>
                </div>
              ))}
            </div>
          </div>
        );
      
      case 'Cache Warmer':
        return (
          <div className="p-4 space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Cache Warmer</h3>
                <p className="text-sm text-gray-600">Automatically warm cache for faster page loads</p>
              </div>
              <button
                onClick={() => setAutomaticWarming(!automaticWarming)}
                className={`flex items-center gap-2 px-4 py-2 rounded-md font-medium transition-colors ${
                  automaticWarming 
                    ? 'bg-green-100 text-green-800' 
                    : 'bg-gray-100 text-gray-600'
                }`}
              >
                {automaticWarming ? <ToggleRight className="w-6 h-6" /> : <ToggleLeft className="w-6 h-6" />}
                Automatic Warming: {automaticWarming ? 'On' : 'Off'}
              </button>
            </div>
            
            {cacheCleared && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-4 flex items-center gap-3">
                <Check className="w-5 h-5 text-green-600" />
                <span className="text-green-800 font-medium">Cache cleared successfully!</span>
              </div>
            )}
            
            <div className="flex gap-4">
              <button
                onClick={handleClearCache}
                className="px-6 py-3 bg-brand-orange text-white rounded-md font-medium hover:bg-orange-600 transition-colors flex items-center gap-2"
              >
                <RefreshCw className="w-5 h-5" />
                Clear All Cache
              </button>
            </div>
            
            {automaticWarming && (
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-center gap-2 text-blue-800">
                  <Zap className="w-5 h-5" />
                  <span className="font-medium">Automatic warming is enabled - cache will be refreshed every 15 minutes</span>
                </div>
              </div>
            )}
          </div>
        );
      
      case 'Diagnostics':
        return (
          <div className="p-4 space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Diagnostics</h3>
                <p className="text-sm text-gray-600">Run health checks on your environment</p>
              </div>
              <button
                onClick={handleRunDiagnostics}
                disabled={diagnosticsRunning}
                className={`px-6 py-3 rounded-md font-medium transition-colors flex items-center gap-2 ${
                  diagnosticsRunning
                    ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
                    : 'bg-brand-orange text-white hover:bg-orange-600'
                }`}
              >
                {diagnosticsRunning ? (
                  <><Loader2 className="w-5 h-5 animate-spin" /> Running...</>
                ) : (
                  <><Activity className="w-5 h-5" /> Run Health Check</>
                )}
              </button>
            </div>
            
            {(diagnosticsOutput.length > 0 || diagnosticsRunning) && (
              <div className="bg-black rounded-lg p-4 font-mono text-sm border border-gray-800">
                <div className="text-green-500 mb-3 border-b border-gray-700 pb-2 flex items-center gap-2">
                  <Terminal className="w-4 h-4" />
                  Terminal Output
                </div>
                <div className="space-y-2 min-h-[120px]">
                  {diagnosticsOutput.map((line, index) => (
                    <div key={index} className="flex items-center gap-2 text-gray-300">
                      <span className="text-green-400">$</span>
                      <span>{line.text}</span>
                      <span className="text-green-400">{line.result}</span>
                    </div>
                  ))}
                  {diagnosticsRunning && (
                    <div className="flex items-center gap-2 text-gray-400">
                      <Loader2 className="w-4 h-4 animate-spin" />
                      <span>Running diagnostics...</span>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="p-6">
      {/* Page Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <h1 className="text-2xl font-bold text-gray-900">
            <OrangeLink href="#" className="hover:text-orange-600">{envDetails.name}</OrangeLink>
          </h1>
          <StatusBadge type="success" label="Live" active={true} />
        </div>
        
        {/* Quick Actions Dropdown */}
        <div className="relative">
          <button
            onClick={() => setQuickActionsOpen(!quickActionsOpen)}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
          >
            <MoreVertical className="w-4 h-4 text-gray-600" />
            <span className="text-sm font-medium text-gray-700">Quick Actions</span>
            <ChevronDown className="w-4 h-4 text-gray-400" />
          </button>
          
          {quickActionsOpen && (
            <>
              <div 
                className="fixed inset-0 z-10" 
                onClick={() => setQuickActionsOpen(false)}
              />
              <div className="absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-md shadow-lg z-20 overflow-hidden">
                <button className="w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                  Restart Service
                </button>
                <button className="w-full px-4 py-2 text-left text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                  Clear Cache
                </button>
              </div>
            </>
          )}
        </div>
      </div>
      
      {/* High-Density Tabs */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        {/* Tab Navigation */}
        <div className="border-b border-gray-200 overflow-x-auto">
          <div className="flex min-w-max">
            {TABS.map((tab) => (
              <button
                key={tab}
                onClick={() => {
                  setTabLoading(true);
                  setTimeout(() => {
                    setActiveTab(tab);
                    setTabLoading(false);
                  }, 150);
                }}
                className={`px-4 py-3 text-sm font-medium whitespace-nowrap transition-colors border-b-2
                  ${activeTab === tab 
                    ? 'text-brand-orange border-brand-orange bg-orange-50' 
                    : 'text-gray-600 border-transparent hover:text-gray-800 hover:bg-gray-50'}`}
              >
                {tab}
              </button>
            ))}
          </div>
        </div>
        
        {/* Tab Content */}
        <div className="p-0 min-h-[200px]">
          {tabLoading ? (
            <div className="p-8 space-y-4 animate-pulse">
              <div className="h-4 bg-gray-200 rounded w-3/4"></div>
              <div className="h-4 bg-gray-200 rounded w-1/2"></div>
              <div className="h-4 bg-gray-200 rounded w-5/6"></div>
            </div>
          ) : (
            <div className="animate-fadeIn">{renderTabContent()}</div>
          )}
        </div>
      </div>
    </div>
  );
}
