import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import OrangeLink from '../components/OrangeLink';
import StatusBadge from '../components/StatusBadge';

// Mock pipeline details data - Matches: Control panel redesign images.pdf → Pipeline Details View
const mockPipelineDetails = {
  1395: {
    id: 1395,
    notes: 'Full Deployment Pipeline for Magento 2 auto generated by Altitude.',
    environment: 'Production',
    rootWebDirectory: 'var/www_m2/example.co.uk',
    rootStorageDirectory: 'var/www_m2/example.co.uk/',
    turnNginxContainerOff: false,
    enableRedisPrefixChange: true,
    deploymentPipeline: 'main-pipeline',
    useCustomBuildCommands: true,
    customBuildCommands: 'npm run build && npm run optimize',
    useCustomDatabaseCommands: false,
    useCustomPostBuildCommands: false,
    customPostBuildCommands: '',
    reloadAdditionalDeployments: true,
  }
};

// Mock monitors data for Pipeline Details
const mockPipelineMonitors = [
  { id: 1, name: 'Deployment Monitor', initiatedBy: 'System', target: 'Production Environment', status: 'active', happenedAt: '2025-12-04 11:30:00' },
  { id: 2, name: 'Health Check', initiatedBy: 'Admin', target: 'Web Pods', status: 'completed', happenedAt: '2025-12-04 10:15:00' },
];

export default function PipelineDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [pipeline, setPipeline] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate loading
    const timer = setTimeout(() => {
      const pipelineData = mockPipelineDetails[id];
      if (pipelineData) {
        setPipeline(pipelineData);
      }
      setLoading(false);
    }, 500);

    return () => clearTimeout(timer);
  }, [id]);

  // Update breadcrumb on mount
  useEffect(() => {
    if (pipeline) {
      const event = new CustomEvent('breadcrumb-update', {
        detail: { company: 'Example Company', website: `Pipeline ${pipeline.id}` }
      });
      window.dispatchEvent(event);
    }
  }, [pipeline]);

  if (loading) {
    return (
      <div className="p-6">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-gray-200 rounded w-1/4"></div>
          <div className="h-4 bg-gray-200 rounded w-1/2"></div>
          <div className="h-4 bg-gray-200 rounded w-3/4"></div>
        </div>
      </div>
    );
  }

  if (!pipeline) {
    return (
      <div className="p-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Pipeline Not Found</h2>
        <OrangeLink to="/environments?tab=Pipelines" className="text-brand-orange">Back to Pipelines</OrangeLink>
      </div>
    );
  }

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate('/environments?tab=Pipelines')}
            className="text-gray-500 hover:text-gray-700"
          >
            ← Back
          </button>
          <h2 className="text-2xl font-bold text-gray-900">Pipeline Details #{pipeline.id}</h2>
        </div>
      </div>

      {/* Pipeline Details - Read-only */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Pipeline Configuration</h3>
        
        <div className="grid grid-cols-2 gap-6">
          {/* ID */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">ID</label>
            <p className="mt-1 font-mono text-sm text-gray-900">{pipeline.id}</p>
          </div>

          {/* Notes */}
          <div className="col-span-2">
            <label className="text-xs text-gray-500 uppercase tracking-wide">Notes</label>
            <p className="mt-1 text-sm text-gray-900">{pipeline.notes}</p>
          </div>

          {/* Environment */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Environment</label>
            <p className="mt-1">
              <OrangeLink to={`/environments`} className="font-medium">
                {pipeline.environment}
              </OrangeLink>
            </p>
          </div>

          {/* Root Web Directory */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Root Web Directory</label>
            <p className="mt-1 font-mono text-sm text-gray-900">{pipeline.rootWebDirectory}</p>
          </div>

          {/* Root Storage Directory */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Root Storage Directory</label>
            <p className="mt-1 font-mono text-sm text-gray-900">{pipeline.rootStorageDirectory}</p>
          </div>

          {/* Turn Nginx Container Off */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Turn Nginx Container Off</label>
            <p className="mt-1">
              <span className={`text-xs px-2 py-1 rounded ${pipeline.turnNginxContainerOff ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                {pipeline.turnNginxContainerOff ? 'Yes' : 'No'}
              </span>
            </p>
          </div>

          {/* Enable Redis prefix change during build */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Enable Redis Prefix Change During Build</label>
            <p className="mt-1">
              <span className={`text-xs px-2 py-1 rounded ${pipeline.enableRedisPrefixChange ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                {pipeline.enableRedisPrefixChange ? 'Yes' : 'No'}
              </span>
            </p>
          </div>

          {/* Deployment Pipeline */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Deployment Pipeline</label>
            <p className="mt-1">
              <OrangeLink to={`/deployments`} className="font-medium">
                {pipeline.deploymentPipeline}
              </OrangeLink>
            </p>
          </div>

          {/* Use Custom Build Commands */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Use Custom Build Commands</label>
            <p className="mt-1">
              <span className={`text-xs px-2 py-1 rounded ${pipeline.useCustomBuildCommands ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                {pipeline.useCustomBuildCommands ? 'Yes' : 'No'}
              </span>
            </p>
          </div>

          {/* Custom Build Commands */}
          {pipeline.useCustomBuildCommands && (
            <div className="col-span-2">
              <label className="text-xs text-gray-500 uppercase tracking-wide">Custom Build Commands</label>
              <p className="mt-1 font-mono text-sm text-gray-900 bg-gray-50 p-2 rounded">{pipeline.customBuildCommands}</p>
            </div>
          )}

          {/* Use Custom Database Commands */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Use Custom Database Commands</label>
            <p className="mt-1">
              <span className={`text-xs px-2 py-1 rounded ${pipeline.useCustomDatabaseCommands ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                {pipeline.useCustomDatabaseCommands ? 'Yes' : 'No'}
              </span>
            </p>
          </div>

          {/* Use Custom Post Build Commands */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Use Custom Post Build Commands</label>
            <p className="mt-1">
              <span className={`text-xs px-2 py-1 rounded ${pipeline.useCustomPostBuildCommands ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                {pipeline.useCustomPostBuildCommands ? 'Yes' : 'No'}
              </span>
            </p>
          </div>

          {/* Custom Post Build Commands */}
          {pipeline.useCustomPostBuildCommands && (
            <div className="col-span-2">
              <label className="text-xs text-gray-500 uppercase tracking-wide">Custom Post Build Commands</label>
              <p className="mt-1 font-mono text-sm text-gray-900 bg-gray-50 p-2 rounded">{pipeline.customPostBuildCommands}</p>
            </div>
          )}

          {/* Reload additional deployments */}
          <div>
            <label className="text-xs text-gray-500 uppercase tracking-wide">Reload Additional Deployments</label>
            <p className="mt-1">
              <span className={`text-xs px-2 py-1 rounded ${pipeline.reloadAdditionalDeployments ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
                {pipeline.reloadAdditionalDeployments ? 'Yes' : 'No'}
              </span>
            </p>
          </div>
        </div>
      </div>

      {/* Monitors Table */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900">Monitors</h3>
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 bg-gray-50">
                <th className="text-left py-3 px-4 font-semibold text-gray-700">ID</th>
                <th className="text-left py-3 px-4 font-semibold text-gray-700">NAME</th>
                <th className="text-left py-3 px-4 font-semibold text-gray-700">INITIATED BY</th>
                <th className="text-left py-3 px-4 font-semibold text-gray-700">TARGET</th>
                <th className="text-left py-3 px-4 font-semibold text-gray-700">STATUS</th>
                <th className="text-left py-3 px-4 font-semibold text-gray-700">HAPPENED AT</th>
              </tr>
            </thead>
            <tbody>
              {mockPipelineMonitors.map((monitor) => (
                <tr key={`monitor-${monitor.id}`} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                  <td className="py-3 px-4 font-mono text-xs text-gray-600">{monitor.id}</td>
                  <td className="py-3 px-4 text-gray-700">{monitor.name}</td>
                  <td className="py-3 px-4 text-gray-700">{monitor.initiatedBy}</td>
                  <td className="py-3 px-4 text-gray-700">{monitor.target}</td>
                  <td className="py-3 px-4">
                    <StatusBadge type={monitor.status === 'active' ? 'success' : monitor.status === 'completed' ? 'pending' : 'error'} />
                  </td>
                  <td className="py-3 px-4 font-mono text-xs text-gray-600">{monitor.happenedAt}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
